using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExampleStreetNameDescomposition
{
    static class AddressData
    {
        public static IEnumerable<string> Streets = new List<string>()
        {
            @"Calle Pampa Perdiz 0",
            @"Pasaje Edmundo Wallis 2047",
            @"Av. Rancagua 3426",
            @"Baquedano 1125",
            @"Thompson 446",
            @"Jose Francisco Vergara 3285",
            @"Jose Francisco Vergara 3375",
            @"Salvador Allende N 2327 ",
            @"Pedro Prado 3318",
            @"Sargento Aldea 2047",
            @"Maipu 260",
            @"Los Aromos 8841 Trocadero",
            @"Manquehue 168 Villa Azul",
            @"La Florida 116",
            @"Diaz Gana 829",
            @"Teniente Ibañez 10016",
            @"Lord Cochrane 2187",
            @"Maipu 344",
            @"Galleguillos Lorca 862 Sector Hospital Militar",
            @"14 De Febrero 2371",
            @"El Correjidor 176 Villa Codelco",
            @"Maipu 374",
            @"Chorrillos 1254 Villa Exotica",
            @"Pasaje Laco 4379",
            @"Franciscanos 2596",
            @"Van Buren 234",
            @"Juan Martinez 322",
            @"Colipi 756",
            @"Portales 765",
            @"Los Carrera 3992",
            @"Van Buren 471",
            @"Walter Vagt 295",
            @"Francisco De Aguirre 161",
            @"Colipi 845 Poblacion Los Sauces",
            @"Talca 1039",
            @"Amancay 736",
            @"Carlos Alvarez 425 El Agrado De Peñuelas",
            @"Lincoyan 218",
            @"Pedro Lagos 801",
            @"Rodolfo Wagenknecht 2990",
            @"Gabriel Gonzalez Videla 2259",
            @"Huanhuali 1062",
            @"Alberto Arenas 3988",
            @"Panoramica 965",
            @"Francisco De Aguirre 160",
            @"Peni 440",
            @"Los Jardines 765",
            @"Pampa Baja 4866 Villa El Indic",
            @"El Salto 1670",
            @"Avenida Estadio 1638",
            @"Balmaceda 3522",
            @"Las Rojas Oriente 1612",
            @"Juan De Dios Peni 251",
            @"Henry Ford 1694",
            @"Las Rojas Oriente 1682",
            @"Arturo Gordon 1204 San Joaquin",
            @"Ernesto Molina 1483",
            @"Estrella 3204",
            @"Las Higueras 851",
            @"David Perry 73",
            @"Vicuña Mackenna 734",
            @"Libertad 622",
            @"Tarapaca 365",
            @"Caupolican 20 Villa Alberto Moath",
            @"Con Con Reñaca 16",
            @"Laura Barros 120",
            @"Pasaje Sendero Uno 1171",
            @"Pablo De Rocha 219",
            @"San Rafael 1441",
            @"Independencia 49",
            @"Palmira Romano Norte 340",
            @"Independencia 5 A",
            @"Santa Lucia 520",
            @"Baquedano 36",
            @"Santa Rita 1411",
            @"Santa Rosa 44",
            @"Menbrillar 551",
            @"Merced 277",
            @"Maipu 19",
            @"Freire 590",
            @"O´ Higgins 1161",
            @"Los Carreras 364",
            @"Thompson 1090",
            @"Jose Miguel Carrera 418 Cartagena",
            @"Santo Domingo 41",
            @"Chacabuco 822",
            @"Traslaviña 1551",
            @"Artemón Cifuentes 721",
            @"Traslaviña 1441",
            @"Freire 210",
            @"Estanque 175",
            @"Subida Ecuador 686, Cerro Panteón",
            @"Brasil 2725",
            @"Fundadores 1030 Villa Fundadores Curauma",
            @"Brasil 2945",
            @"Doctor Montt Saavedra 32",
            @"Garibaldi 151",
            @"Descubridores 1006 Villa Fundadores",
            @"Carrera 303",
            @"Freire 1998",
            @"Arrieta 202",
            @"Arrieta 88",
            @"Pasaje Uno 267 Villa Cosmo",
            @"Diaz 501",
            @"Pasaje Uno 266",
            @"Buenos Aires 1401",
            @"Alvares N 966",
            @"Traslaviña 485",
            @"Lago Verde 15 Altos Del Bosques",
            @"Alvarez 1048 Pasaje Ramirez",
            @"12 Norte 928",
            @"2 Oriente 248",
            @"San Miguel 339 Las Colinas",
            @"3 Norte 551",
            @"Bellavista 358 Concon Sur",
            @"Berger 2728",
            @"Limache 2431",
            @"Los Platanos 2150",
            @"2 Norte 551",
            @"3 Norte 960",
            @"4 Oriente 431",
            @"12 Norte 663",
            @"1 Poniente 312",
            @"Quillota 156",
            @"Diego Portales 1312",
            @"Libertad 1105",
            @"11 Norte 955",
            @"Los Platanos 2701 Miraflores",
            @"Concepcion 311",
            @"Gamero 0169",
            @"Abanderado Ibieta 151",
            @"Republica De Chile 1734",
            @"Illanes 591 Pobla. Urmeneta",
            @"Andres De Alcazar 134",
            @"Freire 220",
            @"Hermano Claudio 451",
            @"Avenida España 81",
            @"Recreo 841",
            @"Pasaje Carlos Olivares 725 Poblacion Manzanal",
            @"Mujica 629",
            @"Campos 763",
            @"Mujica 0229",
            @"Caceres 531",
            @"España 70",
            @"La Compañia 262 Villa Salustro",
            @"Coronel Marzan 108",
            @"Emilio Sotomayor 992",
            @"Olivares 536",
            @"Hermano De La Fuente 580",
            @"German Riesco 1340",
            @"Carlos Walker Martinez 489",
            @"German Riesco 1929",
            @"Aviador Acevedo 201",
            @"Hermano De La Fuente 580",
            @"Villota 525",
            @"Camino A Tutuquen 1800",
            @"Rauquen 1885",
            @"Freire 429",
            @"Merced 557",
            @"Benedicto Leon Esquina Bilbao 301",
            @"Ramon Olate 826",
            @"Yerbas Buenas 0164",
            @"Rengo 702",
            @"Arturo Prat 477",
            @"San Miguel 3171",
            @"3 Poniente 1209",
            @"Granja Darlen 0 3 Montes",
            @"4 Norte 1573",
            @"3 Oriente 2080",
            @"Camino Las Rastras 0 Km 2.5",
            @"1 1/2 Norte 1450 Con 7 Y 8 Oriente",
            @"1 Poniente 1664",
            @"Av. Las Rastras N 1427",
            @"2 Poniente 1139",
            @"Los Duraznos 709",
            @"Av. Manuel Rodriguez 1585",
            @"Carrera 440",
            @"Ecuador 476",
            @"Andres Bello 1577",
            @"Libertad 1057",
            @"Yerbas Buenas 447",
            @"Arauco 316",
            @"Bulnes 724",
            @"San Sebastian 1211",
            @"Mahuzier 92",
            @"Tucapel 16",
            @"Maria Luisa Bombal 15 Villa Francisco Coloane",
            @"Victoria 506",
            @"O´ Higgins 1157",
            @"Trinitarias 121",
            @"Ainavillo 648",
            @"Victoria 1194",
            @"Ramon Carrasco 427 Lomas De San Andres",
            @"Ramon Carrasco N 325",
            @"Janequeo 570",
            @"Cochrane 1133",
            @"Cochrane 1200",
            @"Mac - Iver 1678 Sector Roosvelt",
            @"Bernardo O´Higgins 1518",
            @"Cochrane 870",
            @"Angol 245",
            @"Angol 220",
            @"O´ Higgins 1338",
            @"Ongolmo 777",
            @"Eloisa Urrutia 272 Los Lirios",
            @"Salas 208",
            @"Cochrane 110",
            @"Chacabuco 762",
            @"Angol 361",
            @"Los Militares 500 Lagunilla 1",
            @"Los Copihues N32",
            @"Los Misioneros 1458 Villa Galilea Los Angeles",
            @"Colo Colo 0671",
            @"Arturo Prat 147",
            @"Sevilla 0559",
            @"Jose Manso De Velasco 190",
            @"Juan Antonio Coloma 0311",
            @"Sor Vicenta 2560",
            @"Blanco Encalada 331",
            @"San Cristian 455",
            @"Alberto Causiño 60",
            @"Fresia 25",
            @"Chacabuco 361",
            @"Andalue 1080",
            @"Las Rosas 70 Huertos Familiares",
            @"Las Rosas 70 Huertos Familiares",
            @"Maria Luisa Bombal 15",
            @"Carlos Pezoa Veliz 828",
            @"Antonio Varas 231",
            @"Volcan Choshuenco 4341",
            @"Gomez Carreño 4353",
            @"Radal 559 Higueras",
            @"Anibal Pinto 34",
            @"Maipu 1135",
            @"Portales 550",
            @"Ines De Suarez 1230",
            @"Claro Solar 367",
            @"Thompson 541",
            @"Lynch 646",
            @"Monte Igeldo 01815",
            @"Antonio Varas 264",
            @"San Martin 2351",
            @"Phillippi 643",
            @"General Mackenna 154",
            @"Emilio Delporte 1130",
            @"Valentin Letelier 695",
            @"San Carlos 649",
            @"GALVARINO RIVEROS 1001",
            @"Galvarino Riveros 1015",
            @"Los Carreras 531",
            @"Cervantes 1679",
            @"Juan Mackenna 1246",
            @"Esmeralda 1755",
            @"Andres Bello 853",
            @"Manuel Rodriguez 826",
            @"Nieto De Gaete 1526",
            @"Chaulinec 22 Poblacion Alemana",
            @"Buin 367",
            @"Marcelo Fourcade 4961 Villa Valle Volcanes",
            @"Reloncavi 300 Esquina Sargento Sil Villa Puerta De",
            @"Nueva 1755 Jardines Del Mar",
            @"Libertad 380",
            @"Bilbao 10",
            @"Bilbao 45",
            @"Ochagavia 662",
            @"Puerto Natales 1025",
            @"Benavente 839",
            @"Libertad 545",
            @"Loteo Don Rafael Parcela 22",
            @"Santa Rosa 707",
            @"San Francisco 875",
            @"Baquedano 100",
            @"1 Norte 2233",
            @"Ignacio Serrano 54",
            @"Balmaceda 196",
            @"Balmaceda 309",
            @"Lautaro 1070",
            @"Lautaro N 132",
            @"Diego Portales 12",
            @"Eleuterio Ramirez 580",
            @"Francisco Mozo 320",
            @"Croacia 838",
            @"O´ Higgins 266",
            @"Lautaro Navarro 861",
            @"Señoret 175",
            @"Mejicana 564",
            @"Colon 541",
            @"O´ Higgins 464",
            @"Angamos 199",
            @"Rebeca Aguilar 45",
            @"Maipu 742",
            @"Sarmiento 633",
            @"Jose Menendez 047",
            @"Rebeca Aguilar 78",
            @"Croacia 645",
            @"LAUTARO NAVARRO 861",
            @"Manuel Rodrigez 511",
            @"Carlos Condell 783",
            @"Sargento Aldea 107",
            @"Camino A Lonquen 0",
            @"Torremolinos 7628",
            @"19 De Septiembre 6182",
            @"Las Americas 598",
            @"Valle 0",
            @"Aconcagua 270",
            @"Chicureo 0 Lote D",
            @"Las Encinas 0 Parcela 5 P 5 Q",
            @"La Palmilla 3526",
            @"Independencia 4462",
            @"Huechuraba 1486",
            @"Cardenal Jose Maria Caro 1538",
            @"PARCELA 11 UNION SAN JOSE - LOTE A-3",
            @"Alejandro Guzman 325",
            @"Obispo Manuel Urmaña 91",
            @"Laguna Abascal 284",
            @"Titán 5084",
            @"Las Rejas Sur 640",
            @"Av. Gladys Marín N 6901",
            @"Lib. Bernardo O´Higgins 4221",
            @"Las Araucarias 452",
            @"Rinconada El Salto 805",
            @"Petrohue 1525",
            @"Pasaje Las Golondrinas 6843",
            @"La Viña 1505",
            @"Pedro Fontova 7997",
            @"Pedro Fontova 8077",
            @"Pedro Fontova 7868",
            @"Santa Ines 1433",
            @"Francia 1731",
            @"Fermin Vivaceta 950",
            @"Los Nidos 1548",
            @"19 Norte 1096",
            @"Teniente Bisson 892",
            @"Santa Clara 80",
            @"Almirante Neff 184",
            @"El Parron 110",
            @"Salas 9040",
            @"Pedro Aguirre Cerda 056",
            @"Fernando Rioja 50",
            @"Trinidad 305",
            @"Macul 5950 Alto",
            @"Serafin  Zamora 141",
            @"Rojas Magallanes 2275",
            @"Las Guitarras 7544",
            @"Oaxaca 1244",
            @"La Florida 7705",
            @"Colombia 6885",
            @"Pasaje Ensenada 8971",
            @"Santa Julia 145",
            @"Vicuña Mackenna Poniente 6440",
            @"Venezuela 9157",
            @"Atahualpa 235",
            @"Canada 9290",
            @"Walker Martinez 801",
            @"Rojas Magallanes 293",
            @"Colombia 9143",
            @"Jose Santos Gonzalez Vera 79",
            @"Joaquin Edwards Bello 10430",
            @"Presidente Ovalle 6865",
            @"Santa Rita 1320",
            @"Carlos Ossandon 1645",
            @"Julio Monte Bruno 701",
            @"Larrain 7700",
            @"Monseñor Edwards 1290",
            @"Prinicipe De Gales 8771",
            @"Paula Jaraquemada 50",
            @"La Cañada 7210",
            @"La Montaña 2640 Norte - Valle Grande",
            @"Rio Claro 2621",
            @"Sebastian Elcano1166",
            @"Los Militares 6571",
            @"Las Verbenas 9055 Frente Mall Alto Las Condes",
            @"Chesterton 8677",
            @"Geronimo De Alderete 591",
            @"Las Tranqueras 495",
            @"Campanario 35",
            @"Enrique Foster Sur 460",
            @"Americo Vespucio 188",
            @"Inginiero Blanquer 6504",
            @"4º Centenario 380",
            @"Las Malvas 269",
            @"La Quebrada 14272",
            @"Manquehue Sur 919",
            @"Los Dominicos 7608",
            @"Carlos Xii 221",
            @"Las Condes 7568",
            @"Hermanos Cabot 7211",
            @"Cabildo 6378",
            @"Francisco Bilbao 6060",
            @"Los Dominicos 7796",
            @"Padre Alberto Hurtado 450",
            @"Iv Centenario 320",
            @"Alcantara 980",
            @"Los Militares 6419",
            @"Torres De Paine 7489",
            @"Tomas Moro 1803",
            @"Martin De Zamora 4621",
            @"Guadarrama 1100",
            @"Padre Hurtado Central 1520",
            @"Florencio Barrios ",
            @"Felix De Amesti 237",
            @"Vasco De Gama 4477",
            @"Bello Horizonte 891",
            @"Alexander Fleming 8905",
            @"La Reconquista 816",
            @"TALAVERAS DE LA REINA 380",
            @"Las Condes 10187",
            @"El Rodeo 13479",
            @"Nido De Aguilas 14089",
            @"Camino Los Trapenses 2983",
            @"Robles 13276",
            @"Paihuano 02049",
            @"Quiriquina 3751",
            @"Pablo Neruda 9099",
            @"Los Lirios 1068",
            @"San Pablo 6135",
            @"Portales 6084",
            @"Fobos 5326",
            @"Virgo 47",
            @"Italo Martinez 4664 Villa Macul",
            @"Premio Nobel 2940",
            @"Pedro Prado 4470",
            @"Luis Valenzuela Aris 3762",
            @"Exequiel Fernandez 2406",
            @"Los Academicos 2790",
            @"12 Norte 2065",
            @"Estadio Colo Colo 1873",
            @"Santa Cristina 3141",
            @"Calle 4 102 Pobl. Insa",
            @"Luis Gandarillas 286",
            @"Presidente Riesco 3250",
            @"Mar De Drake 5513 Villa Versalles",
            @"Los Diamantes 0290",
            @"Gustavo Ross 1721",
            @"Pajaritos 1257",
            @"Alcalde Jose Luis Infante Larrain 2092",
            @"Sur 621 Villa Grundig",
            @"Pajaritos 4687",
            @"Arturo Godoy 1555",
            @"Av. Los Pajaritos N 4162",
            @"Nueva San Martin 1843  / 1847",
            @"Centenario 55 Loc 101",
            @"Calle Ilihue  1130",
            @"Collanco 1297",
            @"El Rey 1726",
            @"3 Poniente 250",
            @"Primera Transversal 2892",
            @"San Agustin 250",
            @"Nihue 253 Poblacion El Parque",
            @"Silva Chavez 355",
            @"Silva Chavez 682",
            @"Correa 520",
            @"Coventry 951",
            @"Lo Encalada 927",
            @"Duble Almeyda 1770",
            @"Jose Domingo Cañas 2651",
            @"Ramon Cruz 162",
            @"Pedro Hemrick Ling 782",
            @"Alcalde Eduardo Castillo Velasco 4312",
            @"Duble Almeyda 2904",
            @"Rengo 1268",
            @"Estrella Solitaria 4690",
            @"Ricardo Lyon 3004",
            @"Duble Almeyda 3777",
            @"Beatle Ordoñez 3719",
            @"Alonso De Ercilla N 2980",
            @"Alonso De Ercilla N 2960",
            @"Simón Bolivar N 3724",
            @"Duble Almeyda 1650",
            @"Manuel De Salas 516",
            @"Montenegro 529",
            @"Eduardo Castillo Velasco 3047",
            @"Exequiel Fernandez 476",
            @"Manuel Montt 2499",
            @"Los Agustinos 5590",
            @"Presidente Batlley Ordoñez 4777",
            @"Juan Moya 194",
            @"Jose Domingo Cañas 2937",
            @"Republica De Israel 1777",
            @"Hamburgo 815",
            @"Holanda 3696",
            @"Ignacio Carrera Pinto 298 322-326",
            @"Dos Oriente 764",
            @"Alhue 2589",
            @"San Martin 40",
            @"Maria Ester Garay 049",
            @"Grecia 8255",
            @"Sanchez Fontecilla 13976",
            @"El Valle 8511",
            @"Consistorial 5690",
            @"Calle 1 4372 Villa Gildemaister",
            @"El Valle 8701",
            @"Alberto Valenzuela Llano 2705",
            @"CONSISTORIAL 2600",
            @"Los Leones 2105",
            @"Almirante Riveros 0185",
            @"Hernando De Aguirre 1467",
            @"Eleodoro Yañez 2435",
            @"Francisco Bilbao 2480",
            @"Clemente Fabres 937",
            @"Crucero Exeter 0286",
            @"Suecia 2428",
            @"Maria Luisa Santander 576",
            @"Ricardo Lyon 1437",
            @"Arturo Claro 1363",
            @"Roman Diaz 734",
            @"Juana De Arco 2066",
            @"Antonio Varas 470",
            @"California 2424",
            @"Eliodoro Yañez 1718",
            @"Pocuro 2361",
            @"Padre Letelier 44",
            @"Ricardo Lyon 1664",
            @"Marchant Pereira 2090",
            @"El Cerro 498",
            @"Carlos Antunez 2761",
            @"Suecia 1202",
            @"Seminario 92",
            @"Matilde Salamanca 913",
            @"Alferez Real 1351",
            @"Urbano Vergara 227",
            @"Americo Vespucio 251",
            @"Aeropuerto Arturo Merino B . 0",
            @"Portezuelo 647",
            @"Del Canal 19938",
            @"Del Canal 20136",
            @"Papa San Lino 538 Loc A",
            @"German Ebbenghaus 2822",
            @"Liguria Poniente 1450",
            @"Teniente Bello 55",
            @"Santa Julia 2861",
            @"Arquitecto Eugenio Cerda 132",
            @"Gandarillas 265",
            @"Angel Pimentel 127 Villa Alcantara",
            @"Tolosa 4106 Plazuela Los Toros",
            @"La Montura 7551",
            @"San Carlos 1769",
            @"Coquimbo 2686",
            @"Genaro Salinas 0148",
            @"Concha Y Toro 2588",
            @"Rio Calle Calle 0105",
            @"Cerro Punta Negra 06000",
            @"Noruega 97 Villa Porvenir",
            @"Los Heroes 211",
            @"Las Torres Sur 191",
            @"Manuel Antonio Matta 1576",
            @"Los Carrera 96",
            @"Los Maitenes Oriente 1428",
            @"Los Maitenes Oriente 1484",
            @"Radal 977",
            @"Carrascal 4899",
            @"Victor Hugo 2624",
            @"Nueva Imperial 4786",
            @"Einstein 690",
            @"Maestra Lidia Torres 244",
            @"5 Norte 1910",
            @"Apostol Santiago 1185",
            @"Domingo Santa Maria 2812",
            @"Urmeneta 537",
            @"San Alfonso 541",
            @"Demostenes Rivera 167 Pobl. Ernesto Merino Segura",
            @"Portales 1962",
            @"Garcia De La Huerta 167 Nos",
            @"Colon 550",
            @"Aracena Infanta 170 Depto A",
            @"Las Industrias 4830",
            @"Llano Subercaseaux 4145",
            @"Llano Subercaseaux 4109",
            @"San Ignacio 3949",
            @"Lazo 1231",
            @"San Nicolas 1198",
            @"Florencia 1153",
            @"La Marina 1320",
            @"Teresa Vial 1171",
            @"Llano Subercaseaux 3203",
            @"Bartolo Soto 3721",
            @"4ª Avenida 1319",
            @"Cuarta Avenida 1319",
            @"Tristan Matta 1127",
            @"Real Audiencia 1311",
            @"Almirante Latorre 210",
            @"Santa Monica 2335",
            @"San Alfonso N 1440",
            @"General Jofre 139",
            @"San Isidro 42",
            @"Anibal Letelier 717",
            @"Alonso Ovalle 612",
            @"Serrano 78",
            @"Phillips 84",
            @"Bascuñan Guerrero 1750",
            @"Club Hipico 574",
            @"Esmeralda 77",
            @"Yungay 2210",
            @"Angamos 271",
            @"Principe De Gales 80",
            @"Brasil 73",
            @"San Ignacio 169",
            @"Catedral 1790",
            @"Paris 712 A",
            @"Almirante Hurtado 2037",
            @"Erasmo Escala 2352",
            @"Camino A Lonquen 36 1/2 Sur Paradero",
            @"Juana Canales 1065",
            @"Balmaceda 1183",
            @"Charles Dickens 1439",
            @"Aurelio González 3488",
            @"Carmen Fariña 6532",
            @"Padre Hurtado Norte 1981",
            @"El Coigue 3939",
            @"El Aromo 7366",
            @"Los Dragones 9932",
            @"El Coigue 4274",
            @"El Romance 401",
            @"General Lagos 958",
            @"Bulnes 1300",
            @"Diputado hernan Olave 607 D",
            @"Calle 3 2123 Villa Calle Calle",
            @"Ismael Valdes 245",
            @"Ruben Dario 307",
            @"Garcia Reyes 219",
            @"Picarte 1298",
            @"Arauco 912",
            @"Garcia Reyes 296",
            @"Anibal Pinto 1250",
            @"Rucapillan 484 Sector El Bosque",
            @"Lliuco 506 Villa El Bosque",
            @"Arturo Buitano 152",
            @"Andres Bello 1769",
            @"18 De Septiembre 1326",
            @"Pedro Aguirre Cerda 438",
            @"Sug N 1554",
            @"Munich N 2239",
            @"Galvarino Riveros 1019",
            @"Adrian Zuñiga 822",
            @"Carrera 303",
            @"Fernando Riesco 87"
        };
    }
}
